### ISSUE TITLE
nepali-unicode-converter module showing decoding error

### ISSUE THREAD

**Issue by prem-raj461** [bewakes/nepali-unicode-converter#1]
1. Even when i copy and paste below content
from nepali_unicode_converter.convert import Converter

converter = Converter()
mystring = 'ke chha hajura?'

print(converter.convert(mystring))

it is throwing an error: `` 
"UnicodeDecodeError at /typing_translate_handle 'charmap' codec can't decode byte 0x8d in position 49: character maps to <undefined>"

**Comment by bewakes** [comment]
Hi, thanks for the report. Are you running it in windows or linux?
Also, which python version are you using? And please put the full stacktrace.

**Comment by prem-raj461** [comment]
in window sir,  i am using python 3.8.7

**Comment by bewakes** [comment]
I think I figured out the issue. While reading file I need to have explicitly mentioned utf-8 encoding. I've fixed it now. Can you please try it out again with the newest version? `pip install nepali-unicode-converter==1.0.3`.

**Comment by prem-raj461** [comment]
thank you sir....now its working....

**Comment by bewakes** [comment]
Good to know that!
